version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rtb-app
    container_name: rtb-app
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: rtb-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rtb
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: rtb-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
